### ISSUE TITLE
Games appearing out of order

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#169] opened 2017-06-29 00:31 UTC
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [X] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [X] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed

### Description
I have noticed that in the snapshot versions, my games are appearing in the wrong order.

### Steps to Reproduce the Problem
Open RHRE2

**Expected behavior:** The games are in perfect order.

**Actual behavior:** Some games are out of order.

**Version affected:** 2.16 June 27th Snapshot

### Additional Information
Here is a screenshot of Double Date being in between Donk-Donk English and Donk-Donk Japanese.

![capture](https://user-images.githubusercontent.com/25730122/27666277-4dce647a-5c38-11e7-8e6a-7eec38a5d215.PNG)

**Comment by chrislo27** [comment] 2017-06-29 00:35
Please update your version in your post with the version shown in the editor.

Also, the first step of your reproduction is impossible. :stuck_out_tongue: 

I had a look at games.json and everything seems to be in order. Is this consistent? So far I cannot reproduce this.

**Comment by GuardedLolz** [comment] 2017-06-29 00:54
<iframe width="560" height="315" src="https://www.youtube.com/embed/BWc1E5yhITc" frameborder="0" allowfullscreen></iframe>
#169 is real.

**Comment by chrislo27** [comment] 2017-06-29 00:56
I think I have a fix for this, I'll roll out a B version of the snapshot I just released in a few minutes. (Check the Discord channel for the webhook update).

**Closed** 2017-06-30 05:44 UTC
Labels: bug, fixed
